#!/bin/bash
PROTOBUF=
tar xf $PROTOBUF

pushd $PROTOBUF
./configure --prefix=/opt/protobuf261 && make && make install
popd
#####################################################
LEVELDB=leveldb-master
unzip $LEVELDB

pushd $LEVELDB
make 
cp out-shared /opt/leveldb -a
cp include /opt/leveldb -a
popd

#####################################################
LIBLMDB=liblmdb
tar xf $LIBLMDB
pushd $LIBLMDB
make 
mkdir /opt/liblmdb/lib -p
mkdir /opt/liblmdb/include  -p  
cp *.a *.o /opt/liblmdb/lib -a
cp *.h /opt/liblmdb/include -a
popd
######################################################
OPENBLAS=OpenBLAS
zip OpenBLAS-develop.zip
pushd $OPENBLAS
make PREFIX=/opt/OpenBLAS
make PREFIX=/opt/OpenBLAS install
popd
######################################################
HDF5=hdf5
tar xf $HDF5
pushd $HDF5
./configure --prefix=/opt/hdf5180 && make && make install
popd
######################################################
GLOG=glog
unzip $GLOG
pushd $GLOG
./autogen.sh 
./configure --prefix=/opt/glog/  && make && make install
popd
#######################################################
GFLAGS=gflags-master
unzip $GFLAGS
pushd $GFLAGS
mkdir build
pushd build
cmake .. && make 
popd
mkdir /opt/gflags
cp lib include /opt/gflags/ -a
popd
########################################################
ZLIB=zlib
tar xf $ZLIB
pushd $ZLIB
./configure --prefix=/opt/zlib123 && make && make install
#加入-fPIC
popd
#########################################################
OPENCV330=
pushd $OPENCV330
mkdir build
pushd build
cmake -DCMAKE_INSTALL_PREFIX=/opt/opencv330  ..   && make && make install
popd
popd
########################################################
sudo yum install python-dev
########################################################
BOOST=
tar xf $BOOST
pushd $BOOST
bootstrap.sh
./b2
./b2 install --prefix=/opt/boost 
popd
########################################################
编译caffe

########################################################
rpm -ivh dkms-2.4.0-1.20170926git959bd74.el7.noarch.rpm 
yum install libXext-devel.x86_64
rpm -ivh libvdpau-0.9-1.el6.x86_64.rpm 
rpm -ivh cuda-repo-rhel7-8-0-local-ga2-8.0.61-1.x86_64.rpm
yum clean expire-cache
yum install cuda

nvidia-smi
export CUDA_HOME=/usr/local/cuda
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
